manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com
    # Add the AdeptBLE shield repository link here:
    - name: bildermankawasaki
      url-base: https://github.com/BildermanKawasaki
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # Add the specific project name here:
    - name: zmk-device-adeptble-trackball
      remote: bildermankawasaki
      revision: main
